### ISSUE TITLE
无法调用BaiduAsrPlugin的相关方法

### ISSUE THREAD

**Issue by wangfpp** [rxnh8255/baiduasr#1]
我利用Cordova建了一个项目,按照例子的方法写的程序,一直无法调用BaiduAsrPlugin的方法
index.js
![image](https://user-images.githubusercontent.com/35289556/41269688-36fcf0b8-6e39-11e8-9e8f-c337e6a07ec0.png)

index.html
![image](https://user-images.githubusercontent.com/35289556/41269669-1b88229e-6e39-11e8-953a-e0f9a18d9bb8.png)
实在是找不到错误的原因了

**Comment by wangfpp** [comment]
这个问题已经解决了,又产生了新的问题了。。。哎，如何录音识别呢？

**Comment by wangfpp** [comment]
我的手机系统是Android8.1

**Comment by rxnh8255** [comment]
@wangfpp https://github.com/rxnh8255/baiduasr/blob/master/plugin/README.md
你看这个说明.加到插件里面就可以用了

**Comment by wangfpp** [comment]
是不是的给registerNotify设置一个监听事件呢？

**Comment by rxnh8255** [comment]
@wangfpp 
`window.baiduAsrPlugin.registerNotify(function (res) {
    //res参数都带有一个type
    console.log(res);
},function(err){
    console.log(err);
});`
这样在识别完成后.会返回到res里面.

**Comment by wangfpp** [comment]
@rxnh8255 我的点击事件触发begin事件 就打印出来 识别开始识别结束  怎么就没有录音呢？
baidu不是说是实时流识别的吗？

**Comment by rxnh8255** [comment]
自动打断的.DNN.开始以后你没说话?看AS监控一下log

**Comment by wangfpp** [comment]
我没有用AndroidStudio 直接用Cordova打包然后手机上运行的,这个是调用手机自带的录音还是启动的recoder呢?

**Comment by wangfpp** [comment]
@rxnh8255 这是我的代码部分
![image](https://user-images.githubusercontent.com/35289556/41327274-6ec90024-6ef5-11e8-90cb-731f77c1d4d2.png)
点击开始录音调用asr.begin()的打印信息
![image](https://user-images.githubusercontent.com/35289556/41327308-8c993538-6ef5-11e8-967d-f4b7626828a5.png)

你的testAndroid是能成功的吗？ 能否打包一个APP放到release里面呢？

**Comment by wangfpp** [comment]
@rxnh8255  AndroidStudio 的调试结果
06-13 11:05:49.096 24939-25004/io.cordova.hellocordova I/BaiduAsrPlugin: 开始识别
06-13 11:05:49.105 24939-24939/io.cordova.hellocordova D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: true
06-13 11:05:49.105 24939-24939/io.cordova.hellocordova D/cr_Ime: [InputMethodManagerWrapper.java:68] hideSoftInputFromWindow
06-13 11:05:49.117 24939-25004/io.cordova.hellocordova W/Bundle: Key com.baidu.speech.APP_ID expected Integer but value was a java.lang.String.  The default value 0 was returned.
06-13 11:05:49.117 24939-25004/io.cordova.hellocordova W/Bundle: Attempt to cast generated internal exception:
                                                                 java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
                                                                     at android.os.BaseBundle.getInt(BaseBundle.java:801)
                                                                     at android.os.BaseBundle.getInt(BaseBundle.java:783)
                                                                     at com.baidu.speech.core.ASREngine.initConfig(Unknown Source)
                                                                     at com.baidu.speech.core.ASREngine.postEvent(Unknown Source)
                                                                     at com.baidu.speech.asr.EventManagerAsr.send(Unknown Source)
                                                                     at com.blanktrack.baidu.BaiduAsrPlugin.promptForRecord(BaiduAsrPlugin.java:256)
                                                                     at com.blanktrack.baidu.BaiduAsrPlugin.access$100(BaiduAsrPlugin.java:32)
                                                                     at com.blanktrack.baidu.BaiduAsrPlugin$3.run(BaiduAsrPlugin.java:169)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                     at java.lang.Thread.run(Thread.java:818)
06-13 11:05:49.118 24939-25004/io.cordova.hellocordova E/ASREngine: VAD Model=dnn
06-13 11:05:49.127 24939-25004/io.cordova.hellocordova I/[BDASR_LOG] Policy: use custom galaxy = false
06-13 11:05:49.131 24939-25004/io.cordova.hellocordova D/Device: read deviceID:CB9704829BE6AE4DED8FE2AA04C9AB9D|0
06-13 11:05:49.136 24939-25004/io.cordova.hellocordova W/System.err: java.lang.reflect.InvocationTargetException
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.utils.Util.getDevId(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.utils.Util.pfm(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.utils.Policy.pfm(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.core.ASREngine.initConfig(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.core.ASREngine.postEvent(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.baidu.speech.asr.EventManagerAsr.send(Unknown Source)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.blanktrack.baidu.BaiduAsrPlugin.promptForRecord(BaiduAsrPlugin.java:256)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.blanktrack.baidu.BaiduAsrPlugin.access$100(BaiduAsrPlugin.java:32)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at com.blanktrack.baidu.BaiduAsrPlugin$3.run(BaiduAsrPlugin.java:169)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 11:05:49.137 24939-25004/io.cordova.hellocordova W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err: Caused by: java.lang.SecurityException: getDeviceId: Neither user 10081 nor current process has android.permission.READ_PHONE_STATE.
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err:     at android.os.Parcel.readException(Parcel.java:1620)
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err:     at android.os.Parcel.readException(Parcel.java:1573)
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err:     at com.android.internal.telephony.ITelephony$Stub$Proxy.getDeviceId(ITelephony.java:4730)
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err:     at android.telephony.TelephonyManager.getDeviceId(TelephonyManager.java:758)
06-13 11:05:49.138 24939-25004/io.cordova.hellocordova W/System.err: 	... 13 more
06-13 11:05:49.157 24939-25064/io.cordova.hellocordova I/[BDASR_LOG] MicrophoneServer: add wrap socket, mRemoteOutputStreams size = 1 firstStart = true
06-13 11:05:49.161 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: url = http://vop.baidu.com/v2/up?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &35bb00d, 
06-13 11:05:49.161 24939-25068/io.cordova.hellocordova D/BDSHttpRequestMaker: url: http://vop.baidu.com/v2/up?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b mHostIp: vop.baidu.com &35bb00d, 
06-13 11:05:49.161 24939-24939/io.cordova.hellocordova D/BaiduAsrPlugin: event: name=asr.ready, params={"pid":1536,"sn":"e9ba7f31-a9ec-4e59-85d6-c6937b36840b"}
06-13 11:05:49.172 24939-24939/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 38 : [object Object]
06-13 11:05:49.172 24939-24939/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(38)] "[object Object]", source: file:///android_asset/www/js/index.js (38)
06-13 11:05:49.172 24939-24939/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 40 : 开始识别
06-13 11:05:49.173 24939-24939/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(40)] "开始识别", source: file:///android_asset/www/js/index.js (40)
06-13 11:05:49.177 24939-25064/io.cordova.hellocordova I/[BDASR_LOG] audioSource :: 1
06-13 11:05:49.177 24939-25064/io.cordova.hellocordova I/[BDASR_LOG] MicInputStream: startRecordingAndCheckStatus recorder status is 1
06-13 11:05:49.230 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: url = http://vop.baidu.com/v2/down?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &4bc1bc2, 
06-13 11:05:49.231 24939-25068/io.cordova.hellocordova D/BDSHttpRequestMaker: url: http://vop.baidu.com/v2/down?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b mHostIp: vop.baidu.com &4bc1bc2, 
06-13 11:05:49.250 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: AudioData : mType = 3 | mIsLast = true | mData = 5 &4bc1bc2, 
06-13 11:05:49.251 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: DownloadThread mData[0] = 1 &4bc1bc2, 
06-13 11:05:49.251 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: DownloadThread mData[1] = 0 &4bc1bc2, 
06-13 11:05:49.251 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: DownloadThread mData[2] = 0 &4bc1bc2, 
06-13 11:05:49.251 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: DownloadThread mData[3] = 0 &4bc1bc2, 
06-13 11:05:49.251 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: DownloadThread mData[4] = 3 &4bc1bc2, 
06-13 11:05:49.253 24939-25068/io.cordova.hellocordova I/BDSHttpRequestMaker: sendData  dataType : 0 http://vop.baidu.com/v2/up?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &35bb00d, 
06-13 11:05:49.290 24939-25067/io.cordova.hellocordova I/BDSHttpRequestMaker: readData dataType : 244 http://vop.baidu.com/v2/down?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &4bc1bc2, 
06-13 11:05:49.290 24939-25067/io.cordova.hellocordova I/BDSHttpRequestMaker: readData dataType : 241 http://vop.baidu.com/v2/down?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &4bc1bc2, 
06-13 11:05:49.290 24939-25067/io.cordova.hellocordova I/BDSHttpRequestMaker: response : {"err_msg":"asr authentication operation failed","err_no":-3004,"sn":"e9ba7f31-a9ec-4e59-85d6-c6937b36840b"}
                                                                               http://vop.baidu.com/v2/down?sn=e9ba7f31-a9ec-4e59-85d6-c6937b36840b &4bc1bc2, 
06-13 11:05:49.291 24939-25067/io.cordova.hellocordova I/BDSHttpRequestMaker: Exception &4bc1bc2, 
06-13 11:05:49.291 24939-25067/io.cordova.hellocordova W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URL java.net.HttpURLConnection.getURL()' on a null object reference
06-13 11:05:49.291 24939-25067/io.cordova.hellocordova W/System.err:     at com.baidu.speech.core.BDSHttpRequestMaker.readData(Unknown Source)
06-13 11:05:49.293 24939-25028/io.cordova.hellocordova E/ASREngine: EVoiceRecognitionClientWorkStatusError errorDomain : 33 errorCode : -3004 desc : Server app name unknown. mLastRecognitionResult: 
06-13 11:05:49.293 24939-25028/io.cordova.hellocordova D/ASREngine: generateErrorResult errDomain = 33 errCode = -3004
06-13 11:05:49.294 24939-24939/io.cordova.hellocordova D/BaiduAsrPlugin: event: name=asr.finish, params={"origin_result":{"sn":"","error":4,"desc":"App name unknown","sub_error":4004},"error":4,"desc":"App name unknown","sub_error":4004}
06-13 11:05:49.296 24939-24939/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 38 : [object Object]
06-13 11:05:49.296 24939-24939/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(38)] "[object Object]", source: file:///android_asset/www/js/index.js (38)
06-13 11:05:49.296 24939-24939/io.cordova.hellocordova D/SystemWebChromeClient: file:///android_asset/www/js/index.js: Line 43 : 识别结束
06-13 11:05:49.296 24939-24939/io.cordova.hellocordova I/chromium: [INFO:CONSOLE(43)] "识别结束", source: file:///android_asset/www/js/index.js (43)
06-13 11:05:49.296 24939-24939/io.cordova.hellocordova D/BaiduAsrPlugin: event: name=asr.exit, params=null
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova I/MicrophoneServer: audio mills is 0
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err: java.util.concurrent.ExecutionException: java.io.IOException: Broken pipe
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.util.concurrent.FutureTask.report(FutureTask.java:94)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.util.concurrent.FutureTask.get(FutureTask.java:178)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at com.baidu.speech.audio.MicrophoneServer.run(Unknown Source)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.lang.Thread.run(Thread.java:818)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err: Caused by: java.io.IOException: Broken pipe
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at android.net.LocalSocketImpl.writeba_native(Native Method)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at android.net.LocalSocketImpl.-wrap5(LocalSocketImpl.java)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at android.net.LocalSocketImpl$SocketOutputStream.write(LocalSocketImpl.java:135)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at com.baidu.speech.audio.MicrophoneServer$2.call(Unknown Source)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at com.baidu.speech.audio.MicrophoneServer$2.call(Unknown Source)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova W/System.err: 	... 1 more
06-13 11:05:49.430 24939-26734/io.cordova.hellocordova I/[BDASR_LOG] MicrophoneServer: finally, mRemoteOutputStreams size = 0 firstStart = true

**Comment by rxnh8255** [comment]
你用命令加的插件?BAPPID和SECRETKEY改了吗?

**Comment by wangfpp** [comment]
@rxnh8255   那个都是替换好了的   而且我有重新建立的语音识别项目 重新安装插件也是不行的  我在用AS调试baidu自带的DEMO  看不出来日志哪里有区别
